apps/sso/accounts/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetCompleteView
from django.urls import path
from django.views.generic import TemplateView
from .views import PasswordResetView, PasswordResetConfirmView, PasswordChangeDoneView, PasswordCreateConfirmView
from .views import application, PasswordCreateCompleteView, usernote
from .views import emails, confirm_email
from .views import onetimemessage
from .views import organisation
from .views import password_change, profile, contact, delete_profile

app_name = 'accounts'

urlpatterns = [
    path('', application.UserList.as_view(), name='user_list'),
    path('me/', profile, name='profile'),
    path('add/', application.add_user, name='add_user'),
    path('add/done/<uuid:uuid>/', application.add_user_done, name="add_user_done"),
    path('<uuid:uuid>/', application.update_user, name="update_user"),
    path('<uuid:uuid>/delete/', application.UserDeleteView.as_view(), name="delete_user"),
    path('<uuid:uuid>/notes/delete/', usernote.UserNoteDeleteView.as_view(), name="delete_user_note"),
    path('app_admin/', application.AppAdminUserList.as_view(), name='app_admin_user_list'),
    path('app_admin/<uuid:uuid>/', application.app_admin_update_user, name="app_admin_update_user"),
    path('contact/', contact, name='contact'),
    path('contact_thanks/', TemplateView.as_view(template_name="accounts/contact_thanks.html"), name='contact_thanks'),
    path('email/confirm/<str:uidb64>/<str:token>/', confirm_email, name='confirm_email'),
    path('emails/', emails, name='emails'),
    path('profile/delete/', delete_profile, name='delete_profile'),
    path('password_change/', password_change, name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('password_resend/done/', TemplateView.as_view(template_name="accounts/password_resend_done.html"),
         name='password_resend_done'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
    path('reset/<slug:uidb64>/<slug:token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # must be before 'create/<slug:uidb64>/<slug:token>/'
    path('create/done/<slug:uidb64>/', PasswordCreateCompleteView.as_view(), name='password_create_complete'),
    path('create/<slug:uidb64>/<slug:token>/', PasswordCreateConfirmView.as_view(), name='password_create_confirm'),
    path('organisation_change/<int:pk>/', organisation.OrganisationChangeDetailView.as_view(),
         name='organisationchange_detail'),
    path('organisation_change/me/', organisation.OrganisationChangeUpdateView.as_view(), name='organisationchange_me'),
    path('organisation_change/', organisation.OrganisationChangeList.as_view(), name='organisationchange_list'),
    path('organisation_change/<int:pk>/accept/', organisation.OrganisationChangeAcceptView.as_view(),
         name='organisationchange_accept'),
    path('messages/<uuid:uuid>/', onetimemessage.OneTimeMessageView.as_view(), name="view_message"),
]

apps/sso/api/urls.py
from django.urls import path
from sso.api.views import users, users_v2, organisations, home, countries, regions, country_groups, media, associations

app_name = 'api'

urlpatterns = [
    path('', home.home, name='home'),
    path('user_emails/', users_v2.user_emails, name='user_emails'),
    path('v1/users/', users.get_user_list, name='v1_users'),
    path('v1/users/me/', users.UserDetailView.as_view(), name='v1_users_me'),
    path('v1/users/<uuid:uuid>/', users.UserDetailView.as_view(), name='v1_user'),
    path('v1/users/me/apps/', users.UserDetailView.as_view(is_apps_only=True), name='v1_users_my_apps'),
    path('v1/users/<uuid:uuid>/apps/', users.UserDetailView.as_view(is_apps_only=True),
         name='v1_users_apps'),
    path('v2/users/', users_v2.UserList.as_view(), name='v2_users'),
    path('v2/users/me/', users_v2.MyDetailView.as_view(), name='v2_users_me'),
    path('v2/users/<uuid:uuid>/', users_v2.UserDetailView.as_view(), name='v2_user'),
    path('v2/users/me/navigation/', users_v2.MyGlobalNavigationView.as_view(), name='v2_navigation_me'),
    path('v2/users/<uuid:uuid>/navigation/', users_v2.GlobalNavigationView.as_view(),
         name='v2_navigation'),
    path('v2/organisations/', organisations.OrganisationList.as_view(), name='v2_organisations'),
    path('v2/organisations/<uuid:uuid>/', organisations.OrganisationDetailView.as_view(),
         name='v2_organisation'),
    path('v2/countries/', countries.CountryList.as_view(), name='v2_countries'),
    path('v2/countries/<slug:iso2_code>/', countries.CountryDetailView.as_view(), name='v2_country'),
    path('v2/regions/', regions.RegionList.as_view(), name='v2_regions'),
    path('v2/regions/<uuid:uuid>/', regions.RegionDetailView.as_view(), name='v2_region'),
    path('v2/country_groups/', country_groups.CountryGroupList.as_view(), name='v2_country_groups'),
    path('v2/country_groups/<uuid:uuid>/', country_groups.CountryGroupDetailView.as_view(),
         name='v2_country_group'),
    path('v2/associations/', associations.AssociationList.as_view(), name='v2_associations'),
    path('v2/associations/<uuid:uuid>/', associations.AssociationDetailView.as_view(),
         name='v2_association'),
    path('v2/users/me/picture/', media.MyUserPictureDetailView.as_view(), name='v2_picture_me'),
    path('v2/users/<uuid:uuid>/picture/', media.UserPictureDetailView.as_view(), name='v2_picture'),
]

apps/sso/auth/urls.py
from django.urls import path

from sso.auth.views import LoginView, TokenView, logout
from sso.auth.views.profile import ProfileView, TOTPSetup, PhoneSetupView, AddPhoneView, AddU2FView

app_name = 'auth'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout, name='logout'),
    path('token/<int:device_id>/<str:user_data>/', TokenView.as_view(), name='token'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/totp_setup/', TOTPSetup.as_view(), name='profile_totp_setup'),
    path('profile/add_phone/', AddPhoneView.as_view(), name='add_phone'),
    path('profile/phone_setup/<int:sms_device_id>/', PhoneSetupView.as_view(), name='phone_setup'),
    path('profile/u2f/add_device/', AddU2FView.as_view(), name='u2f_add_device'),
]

apps/sso/emails/urls.py
from django.urls import path
from sso.emails import views

app_name = 'emails'

urlpatterns = [
    path('group/', views.GroupEmailList.as_view(), name='groupemail_list'),
    path('group/<uuid:uuid>/', views.GroupEmailDetailView.as_view(), name='groupemail_detail'),
    path('group/<uuid:uuid>/update/', views.GroupEmailUpdateView.as_view(), name='groupemail_update'),
    path('group/add/', views.GroupEmailCreateView.as_view(), name='groupemail_create'),
    path('group/<uuid:uuid>/forward/add/', views.GroupEmailForwardCreateView.as_view(),
         name='emailforward_create'),
    path('group/<uuid:uuid>/forward/<int:pk>/', views.GroupEmailForwardDeleteView.as_view(),
         name="emailforward_confirm_delete"),
]

apps/sso/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, register_converter
from django.views.generic import RedirectView, TemplateView
from django.views.i18n import JavaScriptCatalog
from smart_selects.views import filterchain
from sso.accounts.forms import UserSelfRegistrationForm2
from sso.admin import sso_admin_site
from sso.oauth2.views import OpenidConfigurationView
from sso.registration.sites import RegistrationSite
from sso.utils.url import UUIDConverter
from sso.views import home

registration_site = RegistrationSite(form_cls=UserSelfRegistrationForm2)

register_converter(UUIDConverter, 'uuid')

urlpatterns = [
    path('', home, name='home'),
    path('.well-known/openid-configuration', OpenidConfigurationView.as_view(), name='openid-configuration'),
    path('jsi18n/', JavaScriptCatalog.as_view(packages=['sso']), name='jsi18n'),
    path('admin/', sso_admin_site.urls),
    path('privacy/', TemplateView.as_view(template_name="privacy.html"), name='privacy'),
    path('about/', RedirectView.as_view(url=settings.SSO_ABOUT, permanent=False), name='about'),
    path('accounts/', include('sso.auth.urls')),
    path('accounts/', include('sso.accounts.urls')),
    path('accounts/', registration_site.urls),
    path('accounts/', include('sso.impersonate.urls')),
    path('organisations/', include('sso.organisations.urls')),
    path('emails/', include('sso.emails.urls')),
    path('oauth2/', include('sso.oauth2.urls')),
    path('api/', include('sso.api.urls')),
    path('chained_filter/organisations/OrganisationCountry/<slug:field>/<slug:value>/', filterchain,
         kwargs={'app': 'organisations', 'model': 'OrganisationCountry', 'manager': 'active_objects'},
         name='chained_filter'),
    path('chained_filter/organisations/AdminRegion/<slug:field>/<slug:value>/', filterchain,
         kwargs={'app': 'organisations', 'model': 'AdminRegion', 'manager': 'active_objects'}, name='chained_filter'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if apps.is_installed('sso.access_requests'):
    urlpatterns += [
        path('extend_access/', include('sso.access_requests.urls')),
    ]

apps/sso/forms/apps.py
from django.apps import AppConfig
from django.utils.translation import ugettext_lazy as _


class FormsConfig(AppConfig):
    name = 'sso.forms'
    verbose_name = _("Forms")
    label = 'sso_forms'

apps/sso/forms/fields.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.gis import forms
from django.contrib.gis.forms import GeometryField
from django.contrib.gis.geos import GEOSGeometry, GEOSException
from django.forms import fields
from django.utils.translation import ugettext_lazy as _
from sso.forms import bootstrap


class EmailFieldLower(fields.EmailField):
    widget = bootstrap.EmailInput(attrs={'size': 50})

    def to_python(self, value):
        email = super().to_python(value).rstrip().lstrip()
        return BaseUserManager.normalize_email(email)

    def __init__(self, max_length=None, min_length=None, *args, **kwargs):
        if 'label' not in kwargs:
            kwargs['label'] = _('email address')
        super().__init__(max_length=max_length, min_length=min_length, *args, **kwargs)


class PointField(GeometryField):
    geom_type = 'POINT'

    def to_python(self, value):
        """Transform the value to a Geometry object."""
        if value in self.empty_values:
            return None

        if not isinstance(value, GEOSGeometry):
            try:
                value = GEOSGeometry(value)
            except (GEOSException, ValueError, TypeError):
                raise forms.ValidationError(self.error_messages['invalid_geom'], code='invalid_geom')
            # in django 2.0 wrong srid is set when using geojson
            value.srid = self.widget.map_srid

        return value

apps/sso/accounts/views/filter.py
import logging

from django.db.models import Q
from django.utils.translation import ugettext_lazy as _
from l10n.models import Country
from sso.views.generic import SearchFilter, ViewChoicesFilter, ViewQuerysetFilter
from sso.accounts.models import ApplicationRole, RoleProfile
from sso.organisations.models import AdminRegion, Organisation, OrganisationCountry

logger = logging.getLogger(__name__)


class UserSearchFilter(SearchFilter):
    search_names = ['username__icontains', 'first_name__icontains', 'last_name__icontains',
                    'useremail__email__icontains']


class UserSearchFilter2(SearchFilter):
    search_names = ['user__username__icontains', 'user__first_name__icontains', 'user__last_name__icontains',
                    'user__useremail__email__icontains']


class IsActiveFilter(ViewChoicesFilter):
    name = 'is_active'
    choices = (('1', _('Active Users')), ('2', _('Inactive Users')))
    select_text = _('active/inactive')
    select_all_text = _("All")
    default = '1'

    def map_to_database(self, qs_name, value):
        return {qs_name: True if (value.pk == "1") else False}


class CountryFilter(ViewQuerysetFilter):
    name = 'country'
    qs_name = 'organisations__organisation_country__country'
    model = Country
    select_text = _('Country')
    select_all_text = _('All Countries')
    all_remove = 'admin_region,center'
    remove = 'admin_region,center,app_role,role_profile,p'
    style = "width: 12em"


class AdminRegionFilter(ViewQuerysetFilter):
    name = 'admin_region'
    qs_name = 'organisations__admin_region'
    model = AdminRegion
    select_text = _('Region')
    select_all_text = _('All Regions')
    all_remove = 'center'
    remove = 'center,app_role,role_profile,p'


class CenterFilter(ViewQuerysetFilter):
    name = 'center'
    qs_name = 'organisations'
    model = Organisation
    select_text = _('Organisation')
    select_all_text = _('All Organisations')
    remove = 'app_role,role_profile,p'
    style = "width: 17em"


class ApplicationRoleFilter(ViewQuerysetFilter):
    name = 'app_role'
    model = ApplicationRole
    select_text = _('Role')
    select_all_text = _('All Roles')

    def apply(self, view, qs, default=''):
        """
        filter with respect to application_roles and role_profiles
        """
        value = self.get_value_from_query_param(view, default)
        if value:
            q = Q(application_roles=value)
            q |= Q(role_profiles__application_roles=value)
            qs = qs.filter(q)
        setattr(view, self.name, value)
        return qs


class RoleProfileFilter(ViewQuerysetFilter):
    name = 'role_profile'
    qs_name = 'role_profiles'
    model = RoleProfile
    select_text = _('Profile')
    select_all_text = _('All Profiles')


########################################################################################
# organisationchange list filter


class OrganisationChangeCountryFilter(ViewQuerysetFilter):
    name = 'country'
    qs_name = 'organisation__organisation_country'
    model = OrganisationCountry
    filter_list = OrganisationCountry.objects.filter(is_active=True).select_related('country')
    select_text = _('Country')
    select_all_text = _('All Countries')
    all_remove = 'admin_region'
    remove = 'admin_region,p'


class OrganisationChangeAdminRegionFilter(ViewQuerysetFilter):
    name = 'admin_region'
    qs_name = 'organisation__admin_region'
    model = AdminRegion
    select_text = _('Region')
    select_all_text = _('All Regions')
    all_remove = ''
    remove = 'p'

apps/sso/accounts/views/onetimemessage.py
import logging

from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView
from django.utils.decorators import method_decorator

from sso.accounts.models import OneTimeMessage

logger = logging.getLogger(__name__)


class OneTimeMessageView(DetailView):
    model = OneTimeMessage
    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user != request.user:
            raise PermissionDenied()
        
        self.object.delete()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

apps/sso/templates/base.html
<!DOCTYPE html>{% load static i18n analytics %}
<html lang="en" class="no-js">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="OpenID Connect Identity Provider">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'ico/favicon.ico' %}" type="image/ico"/>
    <link rel="apple-touch-icon" href="{% static 'ico/apple-touch-icon.png' %}">
    {% block style %}{% if False %}
        <link rel="stylesheet/less" href="{% static stylesheet_less %}">
        <script>less = { env: 'development'};</script>
        <script src="{% static "js/vendor/less-3.9.0.min.js" %}"></script>
        <script>
          less.modifyVars({'@base-dir': '"../less"', '@icon-font-path': '"/static/fonts/"'});
          less.watch();
        </script>
    {% else %}
        <link rel="stylesheet" href="{% static stylesheet %}">{% endif %}
    {% endblock style %}
    {% block extrastyle %}{% endblock %}
    {% block extrahead %}{% endblock %}
    <script>window.__media_prefix__ = "{% filter escapejs %}{% static "" %}{% endfilter %}";</script>
    <script>(function (H) {H.className = H.className.replace(/\bno-js\b/, 'js')})(document.documentElement)</script>
    <script src="{% static "js/vendor/jquery-3.4.1.min.js" %}"></script>
    <script src="{% static "js/vendor/bootstrap-3.4.1.min.js" %}"></script>
    <script src="{% static "js/plugins-1.0.10.js" %}"></script>
    {% block extrascript %}{% endblock extrascript %}
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="{% static "js/vendor/html5shiv-3.7.3.min.js" %}"></script>
      <script src="{% static "js/vendor/respond-1.4.2.min.js" %}"></script>
    <![endif]-->
</head>
<body class="{% block bodyclass %}{% endblock %}">
{% block body %}
    <!--[if lt IE 8]><p class=alert alert-warning>Your browser is <em>ancient!</em> <a href="https://browsehappy.com/">Upgrade to a different browser</a> to experience this site.</p>
    <![endif]-->

    {% block navbar %}
        {% include 'include/global_navigation.html' %}
    {% endblock navbar %}

    <div class="{% block containerclass %}container{% endblock %}">
        {% block breadcrumb %}{% endblock %}

        {% block content %}
            <main>
                <aside>
                    {% block left_content %}
                        {% include 'include/_navigation.html' %}
                    {% endblock left_content %}
                </aside>
                <section>
                    {% block right_content %}<h2>{% trans 'Home' %}</h2>{% endblock %}
                </section>
            </main>
        {% endblock content %}

        <hr>
        {% block footer %}
            <footer>
                <ul>
                    <li><a href="{% url 'about' %}">{% trans 'About us' %}</a></li>
                    <li class="text-muted">·</li>
                    <li><a href="{% url 'privacy' %}">{% trans 'Privacy' %}</a></li>
                    <li class="text-muted">·</li>
                    <li><a href="{% url 'accounts:contact' %}">{% trans 'Feedback' %}</a></li>
                </ul>
            </footer>
        {% endblock footer %}

    </div> <!-- /container -->
{% endblock body %}
{% show_tracker %}
</body>
</html>

apps/sso/templates/base_form.html
{% extends "base_site.html" %}
{% load i18n %}

{% block right_content %}
{% block form %}{% endblock %}
{% endblock %}

apps/sso/templates/base_list.html
{% extends "base_site.html" %}
{% load static %}
{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/select2-bootstrap.css' %}">
{% endblock %}
{% block extrascript %}
    <script src="{% static 'js/vendor/select2.min.js' %}"></script>
{% endblock extrascript %}

apps/sso/templates/base_site.html
{% extends "base.html" %}
{% load i18n %}

{% block brand %}{{ brand }}{% endblock %}
{% block title %}{{ brand }} | {{ title }}{% endblock %}

apps/sso/templates/centered_form.html
{% extends "base_site.html" %}
{% load i18n %}

{% block content %}
<main role="main">
    <div class="dwbn-centered">
        {% block form %}{% endblock %}
    </div>
</main>
{% endblock %}

apps/sso/templates/csrf_failure.html
{% load i18n %}<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% trans 'Forbidden' %} :(</title>
  <style>
    ::-moz-selection { background: #fe57a1; color: #fff; text-shadow: none; }
    ::selection { background: #fe57a1; color: #fff; text-shadow: none; }
    html { padding: 30px 10px; font-size: 20px; line-height: 1.4; color: #737373; background: #f0f0f0; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
    html, input { font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; }
    body { max-width: 500px; _width: 500px; padding: 30px 20px 50px; border: 1px solid #b3b3b3; border-radius: 4px; margin: 0 auto; box-shadow: 0 1px 10px #a7a7a7, inset 0 1px 0 #fff; background: #fcfcfc; }
    h1 { margin: 0 10px; font-size: 50px; text-align: center; }
    h1 span { color: #bbb; }
    h3 { margin: 1.5em 0 0.5em; }
    p { margin: 1em 0; }
    ul { padding: 0 0 0 40px; margin: 1em 0; }
    .container { max-width: 380px; _width: 380px; margin: 0 auto; }
  </style>
</head>
<body>
  <div class="container">
    <h1>{% trans 'Forbidden' %} <span>:(</span></h1>
	  <p>{{ main }}</p>
	{% if no_referer %}
	  <p>
    {% trans "You are seeing this message because this HTTPS site requires a 'Referer header' to be sent by your Web browser, but none was sent. This header is required for security reasons, to ensure that your browser is not being hijacked by third parties." %}
      </p>
      <p>
    {% trans "If you have configured your browser to disable 'Referer' headers, please re-enable them, at least for this site, or for HTTPS connections, or for 'same-origin' requests." %}
      </p>
	{% endif %}
	{% if no_cookie %}
      <p>
    {% trans "You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties." %}
      </p>
      <p>
    {% trans "If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for 'same-origin' requests." %}
      </p>
	{% endif %}  
	
    <p><a href="{{ request.path }}">{% trans "Try again" %}</a></p>
	  
  </div>
</body>
</html>

apps/sso/templates/home.html
{% extends "base_site.html" %}
{% load i18n %}
{% block nav_home_class %}active{% endblock %}


{% block left_content %}
    {% if user.is_authenticated %}{{ block.super }}{% endif %}
{% endblock %}

{% block breadcrumb %}
    {% if user.is_authenticated %}
        <ol class="breadcrumb">
            <li class="active">{% trans 'Home' %}</li>
        </ol>
    {% endif %}
{% endblock breadcrumb %}

{% block right_content %}
    {% if messages %}{% for message in messages %}
        <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>{% endfor %}
    {% endif %}
    {% if user.is_authenticated %}
        {% trans 'Welcome,' %}
        <strong>{% filter force_escape %}{% firstof user.get_full_name user.username %}{% endfilter %}</strong>.
        {% if apps %}
            <h3>{% trans 'Applications' %}</h3>
            <ul>
                {% for app in user.get_apps %}
                    {% if app.url and not app.is_internal %}
                        <li><a href="{{ app.url }}">{{ app.title }}</a></li>{% endif %}
                {% endfor %}
            </ul>
        {% endif %}
    {% else %}
        <h3>{% blocktrans %}One account. All of {{ site_name }}.{% endblocktrans %}</h3>
        <p>
            {% blocktrans %}<a href="{{ login_url }}">Sign in with your {{ brand }} Account</a> and use all {{ site_name }} services.{% endblocktrans %}
        </p>

        {% url 'registration:registration_register' as registration_register_url %}
        {% if registration_register_url and registration_open %}
        <p>
        {% blocktrans %}New at {{ site_name }}? <a href="{{ registration_register_url }}">Register</a>{% endblocktrans %}.
        </p>
        {% endif %}
    {% endif %}

{% endblock right_content %}

apps/sso/templates/privacy.html
{% extends "base_site.html" %}
{% load i18n %}


{% block title %}{{ brand }} | {% trans 'Privacy' %}{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
        <li class="active">{% trans 'Privacy' %}</li>
    </ol>
{% endblock breadcrumb %}


{% block right_content %}
    <h1>{% trans 'Privacy' %}</h1>
    <p>
        {% blocktrans trimmed %}
            Your data will be stored and used by us for the provision of {{ brand }} services.
            Under no circumstances will we give your information to third parties!
        {% endblocktrans %}
    </p>
    {% if data_protection_uri %}
        <p>
            {% blocktrans trimmed %}
                Our data protection declaration can be found on the Website
                <a href="{{ data_protection_uri }}">{{ data_protection_uri }}</a>.
            {% endblocktrans %}
        </p>
    {% endif %}

{% endblock right_content %}