apps/sso/accounts/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetCompleteView
from django.urls import path
from django.views.generic import TemplateView
from .views import PasswordResetView, PasswordResetConfirmView, PasswordChangeDoneView, PasswordCreateConfirmView
from .views import application, PasswordCreateCompleteView, usernote
from .views import emails, confirm_email
from .views import onetimemessage
from .views import organisation
from .views import password_change, profile, contact, delete_profile

app_name = 'accounts'

urlpatterns = [
    path('', application.UserList.as_view(), name='user_list'),
    path('me/', profile, name='profile'),
    path('add/', application.add_user, name='add_user'),
    path('add/done/<uuid:uuid>/', application.add_user_done, name="add_user_done"),
    path('<uuid:uuid>/', application.update_user, name="update_user"),
    path('<uuid:uuid>/delete/', application.UserDeleteView.as_view(), name="delete_user"),
    path('<uuid:uuid>/notes/delete/', usernote.UserNoteDeleteView.as_view(), name="delete_user_note"),
    path('app_admin/', application.AppAdminUserList.as_view(), name='app_admin_user_list'),
    path('app_admin/<uuid:uuid>/', application.app_admin_update_user, name="app_admin_update_user"),
    path('contact/', contact, name='contact'),
    path('contact_thanks/', TemplateView.as_view(template_name="accounts/contact_thanks.html"), name='contact_thanks'),
    path('email/confirm/<str:uidb64>/<str:token>/', confirm_email, name='confirm_email'),
    path('emails/', emails, name='emails'),
    path('profile/delete/', delete_profile, name='delete_profile'),
    path('password_change/', password_change, name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('password_resend/done/', TemplateView.as_view(template_name="accounts/password_resend_done.html"),
         name='password_resend_done'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
    path('reset/<slug:uidb64>/<slug:token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # must be before 'create/<slug:uidb64>/<slug:token>/'
    path('create/done/<slug:uidb64>/', PasswordCreateCompleteView.as_view(), name='password_create_complete'),
    path('create/<slug:uidb64>/<slug:token>/', PasswordCreateConfirmView.as_view(), name='password_create_confirm'),
    path('organisation_change/<int:pk>/', organisation.OrganisationChangeDetailView.as_view(),
         name='organisationchange_detail'),
    path('organisation_change/me/', organisation.OrganisationChangeUpdateView.as_view(), name='organisationchange_me'),
    path('organisation_change/', organisation.OrganisationChangeList.as_view(), name='organisationchange_list'),
    path('organisation_change/<int:pk>/accept/', organisation.OrganisationChangeAcceptView.as_view(),
         name='organisationchange_accept'),
    path('messages/<uuid:uuid>/', onetimemessage.OneTimeMessageView.as_view(), name="view_message"),
]

apps/sso/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, register_converter
from django.views.generic import RedirectView, TemplateView
from django.views.i18n import JavaScriptCatalog
from smart_selects.views import filterchain
from sso.accounts.forms import UserSelfRegistrationForm2
from sso.admin import sso_admin_site
from sso.oauth2.views import OpenidConfigurationView
from sso.registration.sites import RegistrationSite
from sso.utils.url import UUIDConverter
from sso.views import home

registration_site = RegistrationSite(form_cls=UserSelfRegistrationForm2)

register_converter(UUIDConverter, 'uuid')

urlpatterns = [
    path('', home, name='home'),
    path('.well-known/openid-configuration', OpenidConfigurationView.as_view(), name='openid-configuration'),
    path('jsi18n/', JavaScriptCatalog.as_view(packages=['sso']), name='jsi18n'),
    path('admin/', sso_admin_site.urls),
    path('privacy/', TemplateView.as_view(template_name="privacy.html"), name='privacy'),
    path('about/', RedirectView.as_view(url=settings.SSO_ABOUT, permanent=False), name='about'),
    path('accounts/', include('sso.auth.urls')),
    path('accounts/', include('sso.accounts.urls')),
    path('accounts/', registration_site.urls),
    path('accounts/', include('sso.impersonate.urls')),
    path('organisations/', include('sso.organisations.urls')),
    path('emails/', include('sso.emails.urls')),
    path('oauth2/', include('sso.oauth2.urls')),
    path('api/', include('sso.api.urls')),
    path('chained_filter/organisations/OrganisationCountry/<slug:field>/<slug:value>/', filterchain,
         kwargs={'app': 'organisations', 'model': 'OrganisationCountry', 'manager': 'active_objects'},
         name='chained_filter'),
    path('chained_filter/organisations/AdminRegion/<slug:field>/<slug:value>/', filterchain,
         kwargs={'app': 'organisations', 'model': 'AdminRegion', 'manager': 'active_objects'}, name='chained_filter'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if apps.is_installed('sso.access_requests'):
    urlpatterns += [
        path('extend_access/', include('sso.access_requests.urls')),
    ]

apps/sso/accounts/models/application.py
import logging
import uuid
from itertools import chain

from django.conf import settings
from django.contrib.auth.models import Group
from django.core.validators import validate_slug
from django.db import models
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _
from sso.models import AbstractBaseModel, AbstractBaseModelManager

logger = logging.getLogger(__name__)


def get_applicationrole_ids(user_id, filter=None):
    approles1 = ApplicationRole.objects.filter(user__id=user_id).only("id").values_list('id', flat=True)
    approles2 = ApplicationRole.objects.filter(roleprofile__user__id=user_id).only("id").values_list('id', flat=True)
    if filter is not None:
        approles1 = approles1.filter(filter)
        approles2 = approles2.filter(filter)
    # to get a list of distinct values, we create first a set and then a list
    return list(set(chain(approles1, approles2)))


class ApplicationManager(models.Manager):
    def get_by_natural_key(self, uuid):
        return self.get(uuid=uuid)


class Application(models.Model):
    order = models.IntegerField(default=0, help_text=_('Overwrites the alphabetic order.'))
    title = models.CharField(max_length=255)
    url = models.URLField(max_length=2047, blank=True)
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=True)
    global_navigation = models.BooleanField(
        _('global navigation'),
        help_text=_('Designates whether this application should be shown in the global navigation bar.'),
        default=True)
    is_internal = models.BooleanField(_('internal'), default=False)
    is_active = models.BooleanField(_('active'), default=True,
                                    help_text=_('Designates whether this application should be provided.'))
    redirect_to_after_first_login = models.BooleanField(
        _('redirect to after first login'), default=False,
        help_text=_('Designates whether the user should redirected to this app after the first login.'))
    notes = models.TextField(_("Notes"), blank=True, max_length=2048)
    required_scope = models.CharField(_("Required scope"), blank=True, max_length=32,
                                      validators=[validate_slug],
                                      help_text=_('Required OAuth2 scope to get the application roles.'))
    objects = ApplicationManager()

    class Meta:
        ordering = ['order', 'title']
        verbose_name = _("application")
        verbose_name_plural = _("applications")

    @mark_safe
    def link(self):
        if self.url:
            return '<a href="%s">%s</a>' % (self.url, self.url)
        else:
            return ''

    def natural_key(self):
        return self.uuid,

    def __str__(self):
        return self.title


class RoleManager(models.Manager):
    def get_by_natural_key(self, name):
        return self.get(name=name)


class Role(models.Model):
    name = models.CharField(_("name"), unique=True, max_length=255)
    order = models.IntegerField(default=0, help_text=_('Overwrites the alphabetic order.'))
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True,
                              help_text=_('Associated group for SSO internal permission management.'))
    objects = RoleManager()

    class Meta:
        ordering = ['order', 'name']
        verbose_name = _('role')
        verbose_name_plural = _('roles')

    def natural_key(self):
        return self.name,

    def __str__(self):
        return self.name


class ApplicationRoleManager(models.Manager):
    def get_by_natural_key(self, uuid, name):
        return self.get(application__uuid=uuid, role__name=name)


class ApplicationRole(models.Model):
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    is_inheritable_by_org_admin = models.BooleanField(
        _('inheritable by organisation admin'), default=True,
        help_text=_('Designates that the role can inherited by a organisation admin.'))
    is_inheritable_by_global_admin = models.BooleanField(
        _('inheritable by global admin'), default=True,
        help_text=_('Designates that the role can inherited by a global admin.'))
    is_organisation_related = models.BooleanField(
        _('organisation related'), default=False,
        help_text=_('Designates that the role will be deleted in case of a change of the organisation.'))

    objects = ApplicationRoleManager()

    class Meta:
        ordering = ['application', 'role']
        unique_together = (("application", "role"),)
        verbose_name = _('application role')
        verbose_name_plural = _('application roles')

    def natural_key(self):
        return self.application.natural_key() + self.role.natural_key()

    def __str__(self):
        return "%s - %s" % (self.application, self.role)


class RoleProfile(AbstractBaseModel):
    name = models.CharField(_("name"), max_length=255)
    application_roles = models.ManyToManyField(ApplicationRole, blank=True, help_text=_(
        'Associates a group of application roles that are usually assigned together.'))
    order = models.IntegerField(default=0, help_text=_('Overwrites the alphabetic order.'))
    is_inheritable_by_org_admin = models.BooleanField(
        _('inheritable by organisation admin'), default=True,
        help_text=_('Designates that the role profile can inherited by a organisation admin.'))
    is_inheritable_by_global_admin = models.BooleanField(
        _('inheritable by global admin'), default=True,
        help_text=_('Designates that the role profile can inherited by a global admin.'))
    is_organisation_related = models.BooleanField(
        _('organisation related'), default=False,
        help_text=_('Designates that the role will be deleted in case of a change of the organisation.'))

    class Meta(AbstractBaseModel.Meta):
        ordering = ['order', 'name']
        verbose_name = _('role profile')
        verbose_name_plural = _('role profiles')

    def __str__(self):
        return self.name


class UserAssociatedSystem(models.Model):
    """
    Holds mappings to user IDs on other systems
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    userid = models.CharField(max_length=255)

    class Meta:
        verbose_name = _('associated system')
        verbose_name_plural = _('associated systems')
        unique_together = (("application", "userid"),)

    def __str__(self):
        return "%s - %s" % (self.application, self.userid)


class RoleProfileAdmin(AbstractBaseModel):
    role_profile = models.ForeignKey(RoleProfile, on_delete=models.CASCADE, verbose_name=_("role profile"))
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta(AbstractBaseModel.Meta):
        unique_together = (("role_profile", "admin"),)
        verbose_name = _('role profile admin')
        verbose_name_plural = _('role profile admins')


class ApplicationAdmin(AbstractBaseModel):
    application = models.ForeignKey(Application, on_delete=models.CASCADE, verbose_name=_("application"))
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta(AbstractBaseModel.Meta):
        unique_together = (("application", "admin"),)
        verbose_name = _('application admin')
        verbose_name_plural = _('application admins')


class UserNoteManager(AbstractBaseModelManager):
    def create_note(self, user, created_by_user, notes, **kwargs):
        if len(notes) > 0:
            return self.create(user=user, note="\n".join(notes), created_by_user=created_by_user, **kwargs)
        else:
            return self.none()


class UserNote(AbstractBaseModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    note = models.TextField(_("Note"), max_length=1024)
    created_by_user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('created by'), related_name='+',
                                        null=True, on_delete=models.SET_NULL)

    objects = UserNoteManager()

    class Meta(AbstractBaseModel.Meta):
        verbose_name = _('user note')
        verbose_name_plural = _('user notes')

apps/sso/accounts/views/filter.py
import logging

from django.db.models import Q
from django.utils.translation import ugettext_lazy as _
from l10n.models import Country
from sso.views.generic import SearchFilter, ViewChoicesFilter, ViewQuerysetFilter
from sso.accounts.models import ApplicationRole, RoleProfile
from sso.organisations.models import AdminRegion, Organisation, OrganisationCountry

logger = logging.getLogger(__name__)


class UserSearchFilter(SearchFilter):
    search_names = ['username__icontains', 'first_name__icontains', 'last_name__icontains',
                    'useremail__email__icontains']


class UserSearchFilter2(SearchFilter):
    search_names = ['user__username__icontains', 'user__first_name__icontains', 'user__last_name__icontains',
                    'user__useremail__email__icontains']


class IsActiveFilter(ViewChoicesFilter):
    name = 'is_active'
    choices = (('1', _('Active Users')), ('2', _('Inactive Users')))
    select_text = _('active/inactive')
    select_all_text = _("All")
    default = '1'

    def map_to_database(self, qs_name, value):
        return {qs_name: True if (value.pk == "1") else False}


class CountryFilter(ViewQuerysetFilter):
    name = 'country'
    qs_name = 'organisations__organisation_country__country'
    model = Country
    select_text = _('Country')
    select_all_text = _('All Countries')
    all_remove = 'admin_region,center'
    remove = 'admin_region,center,app_role,role_profile,p'
    style = "width: 12em"


class AdminRegionFilter(ViewQuerysetFilter):
    name = 'admin_region'
    qs_name = 'organisations__admin_region'
    model = AdminRegion
    select_text = _('Region')
    select_all_text = _('All Regions')
    all_remove = 'center'
    remove = 'center,app_role,role_profile,p'


class CenterFilter(ViewQuerysetFilter):
    name = 'center'
    qs_name = 'organisations'
    model = Organisation
    select_text = _('Organisation')
    select_all_text = _('All Organisations')
    remove = 'app_role,role_profile,p'
    style = "width: 17em"


class ApplicationRoleFilter(ViewQuerysetFilter):
    name = 'app_role'
    model = ApplicationRole
    select_text = _('Role')
    select_all_text = _('All Roles')

    def apply(self, view, qs, default=''):
        """
        filter with respect to application_roles and role_profiles
        """
        value = self.get_value_from_query_param(view, default)
        if value:
            q = Q(application_roles=value)
            q |= Q(role_profiles__application_roles=value)
            qs = qs.filter(q)
        setattr(view, self.name, value)
        return qs


class RoleProfileFilter(ViewQuerysetFilter):
    name = 'role_profile'
    qs_name = 'role_profiles'
    model = RoleProfile
    select_text = _('Profile')
    select_all_text = _('All Profiles')


########################################################################################
# organisationchange list filter


class OrganisationChangeCountryFilter(ViewQuerysetFilter):
    name = 'country'
    qs_name = 'organisation__organisation_country'
    model = OrganisationCountry
    filter_list = OrganisationCountry.objects.filter(is_active=True).select_related('country')
    select_text = _('Country')
    select_all_text = _('All Countries')
    all_remove = 'admin_region'
    remove = 'admin_region,p'


class OrganisationChangeAdminRegionFilter(ViewQuerysetFilter):
    name = 'admin_region'
    qs_name = 'organisation__admin_region'
    model = AdminRegion
    select_text = _('Region')
    select_all_text = _('All Regions')
    all_remove = ''
    remove = 'p'

apps/sso/accounts/templates/accounts/application/add_user_done.html
{% extends "base_form.html" %}
{% load i18n static %}

{% block title %}{% trans 'Add User' %}{% endblock %}

{% block left_content %}{% include 'include/_navigation.html' with active_navigation="add_user" %}{% endblock left_content %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
        <li><a href="{% url 'accounts:user_list' %}">{% trans 'User List' %}</a></li>
        <li class="active">{% trans 'Add User' %}</li>
    </ol>
{% endblock breadcrumb %}


{% block form %}
    <h1>{% trans 'User added successfully' %}</h1>
    <div class="alert alert-success">
        <strong>{% trans 'A new User was created.' %}</strong><br>
        {% trans 'The new user got an email with instructions for setting a password.' %}<br>
    </div>

    <table class="table">
        <tbody>
        <tr>
            <th>{% trans 'Name' %}:</th>
            <td>{{ new_user.username }}</td>
        </tr>
        <tr>
            <th>{% trans 'First name' %}:</th>
            <td>{{ new_user.first_name }}</td>
        </tr>
        <tr>
            <th>{% trans 'Last name' %}:</th>
            <td>{{ new_user.last_name }}</td>
        </tr>
        <tr>
            <th>{% trans 'Email' %}:</th>
            <td>{{ new_user.primary_email }}</td>
        </tr>
        <tr>
            <th>{% trans 'Organisations' %}:</th>
            <td>{% for organisation in new_user.organisations.all %}{{ organisation }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
        </tr>
        {% for role_profile in new_user.role_profiles.all %}
            <tr>
                <th>{% if forloop.first %}{% trans 'Role profiles' %}: {% endif %}</th>
                <td>{{ role_profile }}</td>
            </tr>
        {% endfor %}
        {% for application_role in new_user.application_roles.all %}
            <tr>
                <th>{% if forloop.first %}{% trans 'Application roles' %}: {% endif %}</th>
                <td>{{ application_role }}</td>
            </tr>
        {% endfor %}
        {% if new_user.usernote_set.all %}
        <tr>
            <th>{% trans 'Notes' %}:</th>
            <td>{{ new_user.usernote_set.all.0.note }}</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    {% if redirect_uri %}<a class="btn btn-default" href="{{ redirect_uri }}">{% trans 'Back' %}</a>{% endif %}
    <a class="btn btn-default" href="{% url 'accounts:update_user' new_user.uuid.hex %}{% if redirect_uri %}?redirect_uri={{ redirect_uri }}{% endif %}">{% trans 'Edit user' %}</a>
    <a class="btn btn-primary" href="{% url 'accounts:add_user' %}{% if redirect_uri %}?redirect_uri={{ redirect_uri }}{% endif %}">{% trans 'Add another user' %}</a>
{% endblock %}

apps/sso/accounts/templates/accounts/application/add_user_form.html
{% extends "base_form.html" %}
{% load i18n static %}

{% block title %}{% trans 'Add User' %}{% endblock %}

{% block extrascript %}{{ form.media }}{% endblock extrascript %}

{% block left_content %}{% include 'include/_navigation.html' with active_navigation="add_user" %}{% endblock left_content %}

{% block breadcrumb %}
<ol class="breadcrumb">
    <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
    <li><a href="{% url 'accounts:user_list' %}">{% trans 'User List' %}</a></li>
    <li class="active">{% trans 'Add User' %}</li>
</ol>
{% endblock breadcrumb %}

{% block form %}
<form class="form-horizontal" method="post">{% csrf_token %}
    {# Include the hidden fields in the form #}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    <div class="">
	    <h3>{% trans 'Add User' %}</h3>
	    <p>
	    {% trans "Please enter the user data for the new account." %}<br>
	    {% trans "After the account was created, the new user will receive an email with instructions for setting a password." %}
	    </p>

	    {% if messages %}{% for message in messages %}
	       <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>{% endfor %}
	    {% endif %}

	    {% if form.errors %}
	        <div class="alert alert-danger">
	        {% if form.errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
	        </div>
	    {% endif %}
    </div>

	<ul class="nav nav-tabs dwbn-nav-tabs">
	   <li class="active"><a href="#user" data-toggle="tab">{% trans 'User data' %}</a></li>
	   <li><a href="#app_roles" data-toggle="tab">{{ form.application_roles.label }}</a></li>
       <li><a href="#notes" data-toggle="tab">{{ form.notes.label }}</a></li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content">
	   <div class="tab-pane active" id="user">
	       <div>
             {% include 'include/_field.html' with field=form.first_name %}
             {% include 'include/_field.html' with field=form.last_name %}
             {% include 'include/_field.html' with field=form.gender %}
             {% include 'include/_field.html' with field=form.dob %}
             {% include 'include/_field.html' with field=form.organisations %}
             {% include 'include/_email_field.html' with field=form.email %}
             {% include 'accounts/includes/_profiles_field.html' with field=form.role_profiles %}
          </div>
       </div>
	   <div class="tab-pane" id="app_roles">
	       <div>
             {% with field=form.application_roles %}
             <div class="form-group {% if field.errors %}has-error{% endif %}">
                <div class="dwbn-form-control_lg">
                 {{ field }}{% if field.help_text or field.errors %}<span class="help-block">{{ field.help_text }} {% for error in field.errors %}{{ error }} {% endfor %}</span>{% endif %}
                </div>
             </div>
             {% endwith %}
          </div>
	   </div>
       <div class="tab-pane" id="notes">
            <div>
                {% with field=form.notes %}
                  <div class="form-group {% if field.errors %}has-error{% endif %}">
                    <div class="dwbn-form-control_lg">
                       {{ field }}{% if field.help_text or field.errors %}<span class="help-inline">{{ field.help_text }} {% for error in field.errors %}{{ error }} {% endfor %}</span>{% endif %}
                     </div>
                  </div>
                {% endwith %}
            </div>
       </div>
   </div>

    <div class="form-group">
      <div class="dwbn-form-submit">
          {% if redirect_uri %}<a class="btn btn-default" href="{{ redirect_uri }}">{% trans 'Back' %}</a>{% endif %}
          <button type="submit" class="btn btn-primary">{% trans 'Add User and Send Invitation Mail' %}</button>
      </div>
    </div>

</form>
{% endblock %}

apps/sso/accounts/templates/accounts/application/update_center_form.html
{% extends "base_form.html" %}
{% load i18n static %}
{% load thumbnail %}

{% block title %}{% trans 'Change User' %}{% endblock %}

{% block extrascript %}
    {{ media }}
    <script src="{% static "js/formsets-1.2.js" %}"></script>
{% endblock extrascript %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
        <li><a href="{% url 'accounts:user_list' %}">{% trans 'User List' %}</a></li>
        <li class="active">{% trans 'Change User' %}</li>
    </ol>
{% endblock breadcrumb %}

{% block form %}
    <form class="form-horizontal" method="post" data-active="{{ active }}">{% csrf_token %}
        {# Include the hidden fields in the form #}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        <div class="">
            <h3>{{ title }} - {{ form.user.first_name }} {{ form.user.last_name }}</h3>

            {% if messages %}{% for message in messages %}
                <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>
            {% endfor %}
            {% endif %}

            {% if errors %}
                <div class="alert alert-danger">
                    {% if errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}
                        {% trans "Please correct the errors below." %}{% endif %}
                </div>
            {% endif %}
        </div>

        <ul class="nav nav-tabs dwbn-nav-tabs" id="myTab">
            <li class="{% if not active or active == "object" %}active{% endif %}">
                <a data-toggle="tab"
                   href="#object">{% trans 'User data' %}</a>
            </li>
            <li><a data-toggle="tab" href="#app_roles">{{ form.application_roles.label }}</a></li>
            <li><a data-toggle="tab" href="#notes">{{ form.notes.label }}</a></li>
        </ul>

        <div class="tab-content">
            <div class="tab-pane {% if not active or active == "object" %}active{% endif %}" id="object">
                {% if not form.user.is_active %}
                    {% include 'include/_static_field.html' with field=form.status extra_class="bg-danger" %}
                {% endif %}
                {% include 'include/_field.html' with field=form.account_type %}
                {% include 'include/_field.html' with field=form.username %}
                {% include 'include/_field.html' with field=form.organisation %}
                {% include 'include/_field.html' with field=form.email %}
                {% include 'accounts/includes/_profiles_field.html' with field=form.role_profiles %}
            </div>
            <div class="tab-pane" id="app_roles">
                {% include 'accounts/includes/_app_roles_field.html' with field=form.application_roles %}
            </div>
            <div class="tab-pane" id="notes">
                {% include 'include/_usernote_field.html' with field=form.notes %}
            </div>

        </div>
        <!-- /.tab-content -->

        <div class="form-group">
            <div class="dwbn-form-control_lg">
                {% if form.user.is_active %}
                    <button type="submit" class="btn btn-default" name="_deactivate">{% trans 'Block User' %}</button>
                {% else %}
                    <button type="submit" class="btn btn-success" name="_activate">{% trans 'Activate User' %}</button>
                {% endif %}
                {% if perms.accounts.delete_user and not form.user.is_active %}
                    <a class="btn btn-default" href="{% url 'accounts:delete_user' form.user.uuid.hex %}">{% trans 'Delete User' %}</a>
                {% endif %}
                {% if perms.accounts.add_user %}
                    <button type="submit" class="btn btn-default" name="_addanother">{% trans 'Save and add another' %}</button>
                {% endif %}
                {% if not logged_in %}
                    <button type="submit" class="btn btn-default" name="_resend_invitation">{% trans 'Save and resend Invitation Mail' %}</button>
                {% endif %}
                <button type="submit" class="btn btn-default" name="_continue">{% trans 'Save and continue editing' %}</button>
                {% if is_validation_period_active %}
                    <button type="submit" class="btn btn-default" name="_extend_validity">{% trans 'Save and extend validity' %}</button>
                {% endif %}
                <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
            </div>
        </div>

    </form>
{% endblock %}