apps/sso/organisations/urls.py
from django.urls import path
from . import views
from .views import region, country

app_name = 'organisations'

urlpatterns = [
    path('', views.OrganisationList.as_view(), name='organisation_list'),
    path('export.csv', views.OrganisationList.as_view(export=True, filename="organisations.csv",
                                                      content_type='text/csv;charset=utf-8;'),
         name='organisation_list_csv'),
    path('export.txt', views.OrganisationList.as_view(export=True, content_type='text;charset=utf-8;'),
         name='organisation_list_txt'),
    path('me/', views.MyOrganisationDetailView.as_view(), name='my_organisation_detail'),
    path('<uuid:uuid>/', views.OrganisationDetailView.as_view(), name='organisation_detail'),
    path('<uuid:uuid>/update/', views.OrganisationUpdateView.as_view(), name='organisation_update'),
    path('<uuid:uuid>/delete/', views.OrganisationDeleteView.as_view(), name='organisation_delete'),
    path('<uuid:uuid>/picture/', views.OrganisationPictureUpdateView.as_view(),
         name='organisation_picture_update'),
    path('add/', views.OrganisationCreateView.as_view(), name='organisation_create'),
    path('region/', region.AdminRegionList.as_view(), name='adminregion_list'),
    path('region/<uuid:uuid>/', region.AdminRegionDetailView.as_view(), name='adminregion_detail'),
    path('region/<uuid:uuid>/update/', region.AdminRegionUpdateView.as_view(), name='adminregion_update'),
    path('region/add/', region.AdminRegionCreateView.as_view(), name='adminregion_create'),
    path('country/', country.OrganisationCountryList.as_view(), name='organisationcountry_list'),
    path('country/<uuid:uuid>/', country.OrganisationCountryDetailView.as_view(),
         name='organisationcountry_detail'),
    path('country/<uuid:uuid>/update/', country.OrganisationCountryUpdateView.as_view(),
         name='organisationcountry_update'),
    path('country/add/', country.OrganisationCountryCreateView.as_view(), name='organisationcountry_create'),
]

apps/sso/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, register_converter
from django.views.generic import RedirectView, TemplateView
from django.views.i18n import JavaScriptCatalog
from smart_selects.views import filterchain
from sso.accounts.forms import UserSelfRegistrationForm2
from sso.admin import sso_admin_site
from sso.oauth2.views import OpenidConfigurationView
from sso.registration.sites import RegistrationSite
from sso.utils.url import UUIDConverter
from sso.views import home

registration_site = RegistrationSite(form_cls=UserSelfRegistrationForm2)

register_converter(UUIDConverter, 'uuid')

urlpatterns = [
    path('', home, name='home'),
    path('.well-known/openid-configuration', OpenidConfigurationView.as_view(), name='openid-configuration'),
    path('jsi18n/', JavaScriptCatalog.as_view(packages=['sso']), name='jsi18n'),
    path('admin/', sso_admin_site.urls),
    path('privacy/', TemplateView.as_view(template_name="privacy.html"), name='privacy'),
    path('about/', RedirectView.as_view(url=settings.SSO_ABOUT, permanent=False), name='about'),
    path('accounts/', include('sso.auth.urls')),
    path('accounts/', include('sso.accounts.urls')),
    path('accounts/', registration_site.urls),
    path('accounts/', include('sso.impersonate.urls')),
    path('organisations/', include('sso.organisations.urls')),
    path('emails/', include('sso.emails.urls')),
    path('oauth2/', include('sso.oauth2.urls')),
    path('api/', include('sso.api.urls')),
    path('chained_filter/organisations/OrganisationCountry/<slug:field>/<slug:value>/', filterchain,
         kwargs={'app': 'organisations', 'model': 'OrganisationCountry', 'manager': 'active_objects'},
         name='chained_filter'),
    path('chained_filter/organisations/AdminRegion/<slug:field>/<slug:value>/', filterchain,
         kwargs={'app': 'organisations', 'model': 'AdminRegion', 'manager': 'active_objects'}, name='chained_filter'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if apps.is_installed('sso.access_requests'):
    urlpatterns += [
        path('extend_access/', include('sso.access_requests.urls')),
    ]

apps/sso/organisations/models.py
import logging
import re

from pytz import timezone, common_timezones, UnknownTimeZoneError
from sorl import thumbnail

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.gis import measure
from django.contrib.gis.db.models import PolygonField, PointField
from django.contrib.gis.db.models.functions import Distance
from django.core.cache import cache
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.db import models
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.timezone import localtime, now
from django.utils.translation import pgettext_lazy, ugettext_lazy as _
from l10n.models import Country
from smart_selects.db_fields import ChainedForeignKey
from sso.decorators import memoize
from sso.emails.models import Email, CENTER_EMAIL_TYPE, COUNTRY_EMAIL_TYPE, REGION_EMAIL_TYPE, COUNTRY_GROUP_EMAIL_TYPE
from sso.fields import URLFieldEx, URLArrayField
from sso.models import AbstractBaseModel, AddressMixin, PhoneNumberMixin, ensure_single_primary, get_filename

logger = logging.getLogger(__name__)


def is_validation_period_active(organisation):
    if settings.SSO_VALIDATION_PERIOD_IS_ACTIVE:
        if settings.SSO_VALIDATION_PERIOD_IS_ACTIVE_FOR_ALL:
            return True
        else:
            return organisation and organisation.uses_user_activation
    else:
        return False


def is_validation_period_active_for_user(user):
    if user.is_center or user.is_service:
        return False
    try:
        user_organisation = user.organisations.first()
    except ObjectDoesNotExist:
        user_organisation = None

    return is_validation_period_active(user_organisation)


class TzWorld(models.Model):
    """
    table from http://efele.net/maps/tz/world/ with timezones and areas
    infos; http://shisaa.jp/postset/postgis-and-postgresql-in-action-timezones.html
    """
    gid = models.AutoField(primary_key=True)
    tzid = models.CharField(max_length=30, blank=True)
    geom = PolygonField(blank=True, null=True)

    class Meta:
        # managed = False
        db_table = 'tz_world'
        required_db_features = ['gis_enabled']


class CountryGroup(AbstractBaseModel):
    name = models.CharField(_("name"), max_length=255)
    email = models.OneToOneField(Email, on_delete=models.SET_NULL, verbose_name=_("email address"), blank=True,
                                 null=True, limit_choices_to={'email_type': COUNTRY_GROUP_EMAIL_TYPE})
    homepage = models.URLField(_("homepage"), blank=True, )

    class Meta(AbstractBaseModel.Meta):
        verbose_name = _('Country group')
        verbose_name_plural = _('Country groups')
        ordering = ['name']

    def __str__(self):
        return self.name


class Association(AbstractBaseModel):
    name = models.CharField(_("name"), max_length=255)
    homepage = models.URLField(_("homepage"), blank=True)
    email_domain = models.CharField(_("email domain"), blank=True, max_length=254)
    is_active = models.BooleanField(_('active'), default=True,
                                    help_text=_('Designates whether this association should be treated as '
                                                'active. Unselect this instead of deleting the association.'))
    is_external = models.BooleanField(_('external'), default=False,
                                      help_text=_('Designates whether this association is managed externally.'))
    is_selectable = models.BooleanField(_('selectable'), default=True, help_text=_(
        'Designates whether the organisations of this association can be selected by/assigned to users.'))

    class Meta(AbstractBaseModel.Meta):
        verbose_name = _('Association')
        verbose_name_plural = _('Associations')
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('api:v2_association', kwargs={'uuid': self.uuid.hex})


def default_association():
    if multiple_associations():
        return Association.objects.get_by_natural_key(settings.SSO_DEFAULT_ASSOCIATION_UUID).pk
    else:
        return Association.objects.first().pk


def multiple_associations():
    count = cache.get_or_set('association__count', Association.objects.count)
    return count > 1


def region_count():
    return cache.get_or_set('region__count', AdminRegion.objects.count)


class ActiveOrganisationCountryManager(models.Manager):
    """
    custom manager for using in chained field
    """

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class ExtraOrganisationCountryManager(models.Model):
    active_objects = ActiveOrganisationCountryManager()

    class Meta:
        abstract = True


class OrganisationCountry(AbstractBaseModel, ExtraOrganisationCountryManager):
    association = models.ForeignKey(Association, on_delete=models.CASCADE, verbose_name=_("association"),
                                    default=default_association, limit_choices_to={'is_active': True})
    country = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name=_("country"),
                                limit_choices_to={'active': True})
    country_groups = models.ManyToManyField(CountryGroup, blank=True, related_name='countries')
    homepage = models.URLField(_("homepage"), blank=True, )
    email = models.ForeignKey(Email, verbose_name=_("email address"), blank=True, null=True,
                              limit_choices_to={'email_type': COUNTRY_EMAIL_TYPE},
                              on_delete=models.SET_NULL)
    is_active = models.BooleanField(_('active'), default=True,
                                    help_text=_('Designates whether this country should be treated as '
                                                'active. Unselect this instead of deleting the country.'))

    class Meta(AbstractBaseModel.Meta):
        verbose_name = _('Country')
        verbose_name_plural = _('Countries')
        ordering = ['country']
        unique_together = (("country", "association"),)

    def __str__(self):
        # return u"%s" % self.country
        if multiple_associations():
            return "%s, %s" % (self.country, self.association)
        else:
            return '%s' % self.country

    def get_absolute_url(self):
        return reverse('organisations:organisationcountry_detail', kwargs={'uuid': self.uuid.hex, })

    @memoize
    def get_last_modified_deep(self):
        last_modified_list = [self.last_modified, self.country.last_modified]

        last_modified = max(last_modified_list)
        return last_modified


class ActiveAdminRegionManager(models.Manager):
    """
    custom manager for using in chained field
    """

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class ExtraManager(models.Model):
    active_objects = ActiveAdminRegionManager()

    class Meta:
        abstract = True


class AdminRegion(AbstractBaseModel, ExtraManager):
    name = models.CharField(_("name"), max_length=255)
    homepage = models.URLField(_("homepage"), blank=True)
    organisation_country = models.ForeignKey(OrganisationCountry, verbose_name=_("country"), null=True,
                                             limit_choices_to={'is_active': True},
                                             on_delete=models.SET_NULL)
    email = models.OneToOneField(Email, verbose_name=_("email address"), blank=True, null=True,
                                 limit_choices_to={'email_type': REGION_EMAIL_TYPE},
                                 on_delete=models.SET_NULL)
    is_active = models.BooleanField(_('active'), default=True,
                                    help_text=_('Designates whether this region should be treated as '
                                                'active. Unselect this instead of deleting the region.'))
    slug = models.SlugField(_("Slug Name"), blank=True, unique=True,
                            help_text=_("Used for URLs, auto-generated from name if blank"), max_length=255)

    class Meta(AbstractBaseModel.Meta):
        verbose_name = _('Region')
        verbose_name_plural = _('Regions')
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('organisations:adminregion_detail', kwargs={'uuid': self.uuid.hex})


def get_near_organisations(current_point, distance_from_point=None, qs=None, order=True):
    """
    get all centers with the distance from current_point
    where the distance is less than distance_from_point
    """
    if current_point is None:
        return Organisation.objects.none()
    if qs is not None:
        organisations = qs
    else:
        organisations = Organisation.objects.all()
    if distance_from_point:
        organisations = organisations.filter(location__distance_lt=(current_point, measure.D(**distance_from_point)))
    organisations = organisations.annotate(distance=Distance('location', current_point))
    if order:
        return organisations.order_by('distance')
    else:
        return organisations


class Organisation(AbstractBaseModel):
    COORDINATES_TYPE_CHOICES = (
        # ('1', _('Unknown')),
        ('2', _('City/Village')),
        ('3', _('Exact')),
        ('4', _('Nearby')),
    )
    _center_type_choices = {}
    for choice in settings.CENTER_TYPE_CHOICES:
        _center_type_choices[choice[0]] = choice[1]

    def center_type_desc(self):
        return self._center_type_choices.get(self.center_type, '')

    _original_location = None

    name = models.CharField(_("name"), max_length=255)
    order = models.IntegerField(default=0, help_text=_('Overwrites the alphabetic order.'))
    name_native = models.CharField(_("name in native language"), max_length=255, blank=True)

apps/sso/organisations/templates/organisations/adminregion_detail.html
{% extends "base_form.html" %}
{% load i18n static %}

{% block title %}{% trans 'Region Details' %}{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
        <li><a href="{% url 'organisations:adminregion_list' %}">{% trans 'Regions' %}</a></li>
        <li class="active">{% trans 'Region Details' %}</li>
    </ol>
{% endblock breadcrumb %}


{% block form %}

    {% block message %}{% endblock %}

    <h3>{{ object.name }}</h3>

    {% if messages %}{% for message in messages %}
        <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>{% endfor %}
    {% endif %}

    <div class="row">
        <div class="dwbn-label">{% trans 'Name' %}:</div>
        <div class="dwbn-content">{{ object.name }}</div>
    </div>
    <div class="row">
        <div class="dwbn-label">{% trans 'Country' %}:</div>
        <div class="dwbn-content">{{ object.country }}</div>
    </div>
    <div class="row">
        <div class="dwbn-label">{% trans 'Homepage' %}:</div>
        <div class="dwbn-content"><a href="{{ object.homepage }}">{{ object.homepage }}</a></div>
    </div>
    <div class="row">
        <div class="dwbn-label">{% trans 'Active' %}:</div>
        <div class="dwbn-content"><span
                class="glyphicon glyphicon-{% if object.is_active %}ok-sign{% else %}minus-sign{% endif %}"></span>
        </div>
    </div>

    {% if object.email %}
        <div class="row">
            <div class="dwbn-label">{% trans 'Email address' %}:</div>
            <div class="dwbn-content">{{ object.email }}</div>
        </div>
        {% if perms.organisations.change_adminregion and has_region_access %}
            {% for emailforward in  object.email.emailforward_set.all %}
                <div class="row">
                    <div class="dwbn-label">{% trans 'Email forwarding address' %}:</div>
                    <div class="dwbn-content">{{ emailforward }}</div>
                </div>
            {% endfor %}
            {% for emailalias in  object.email.emailalias_set.all %}
                <div class="row">
                    <div class="dwbn-label">{% trans 'Email alias address' %}:</div>
                    <div class="dwbn-content">{{ emailalias }}</div>
                </div>
            {% endfor %}
        {% endif %}
    {% endif %}
    <br>

    <div class="form-group">
        <div class="dwbn-form-control_lg">
            {% block submit_group %}

                {% if perms.organisations.change_adminregion and has_region_access %}
                    <a class="btn btn-primary"
                       href="{% url 'organisations:adminregion_update' object.uuid.hex %}">{% trans 'Update' %}</a>
                {% endif %}

            {% endblock %}
        </div>
    </div>

{% endblock %}

apps/sso/organisations/templates/organisations/organisation_confirm_delete.html
{% extends "organisations/organisation_detail.html" %}
{% load i18n %}

{% block title %}{% trans 'Delete Organisation' %}{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
    <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
    <li><a href="{% url 'organisations:organisation_list' %}">{% trans 'Organisations' %}</a></li>
    <li class="active">{% trans 'Delete Organisation' %}</li>
</ol> 
{% endblock breadcrumb %}


{% block message %}
<div class="alert alert-danger">
{% trans "Please confirm deleting this organisation" %}
</div>
{% endblock %}


{% block submit_group %}
<form class="form-horizontal" method="post">{% csrf_token %}  
	<button type="submit" class="btn btn-danger">{% trans 'Confirm Delete Organisation' %}</button>
	<a class="btn btn-primary" href="{% url 'organisations:organisation_detail' object.uuid.hex %}">{% trans 'Cancel' %}</a>
</form>
{% endblock %}

apps/sso/organisations/templates/organisations/organisation_form.html
{% extends "base_form.html" %}
{% load i18n static %}

{% block title %}{% trans 'Organisation Details' %}{% endblock %}

{% block extrascript %}{{ media }}
    <script src="{% url 'jsi18n' %}"></script>
{% endblock extrascript %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
        <li><a href="{% url 'organisations:organisation_list' %}">{% trans 'Organisations' %}</a></li>
        <li><a href="{% url 'organisations:organisation_detail' object.uuid.hex %}">{{ object.name }}</a></li>
        <li class="active">{% trans 'Update Organisation' %}</li>
    </ol>
{% endblock breadcrumb %}

{% block form %}
    <form class="form-horizontal" method="post" data-active="{{ active }}">{% csrf_token %}
        {# Include the hidden fields in the form #}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {#<input class="hidden" name="redirect_uri" value="{{ redirect_uri }}"/>#}

        <div class="">
            <h3>{{ object.get_center_type_display }} {{ object.name }}</h3>

            {% if messages %}{% for message in messages %}
                <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>
            {% endfor %}
            {% endif %}

            {% if errors %}
                <div class="alert alert-danger">
                    {% if errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}
                        {% trans "Please correct the errors below." %}{% endif %}
                </div>
            {% endif %}

            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}

        </div>

        <ul class="nav nav-tabs dwbn-nav-tabs" id="myTab">
            <li class="{% if not active or active == "object" %}active{% endif %}">
                <a data-toggle="tab"
                   href="#object">{% trans 'Basis Data' %}</a>
            </li>
            {% for formset in formsets %}
                <li class="{% if active == formset.prefix %}active{% endif %}">
                    <a data-toggle="tab"
                       href="#{{ formset.prefix }}">{{ formset.form.opts.verbose_name_plural|title }}</a>
                </li>
            {% endfor %}
        </ul>

        <div class="tab-content">
            <div class="tab-pane {% if not active or active == "object" %}active{% endif %}" id="object">
                {% include 'include/_field.html' with field=form.name %}
                {% include 'include/_field.html' with field=form.name_native %}
                {% include 'include/_field.html' with field=form.center_type %}
                {% include 'include/_field.html' with field=form.association %}
                {% include 'include/_field.html' with field=form.organisation_country %}
                {% include 'include/_field.html' with field=form.admin_region %}
                {% include 'include/_field.html' with field=form.email_value %}
                {% include 'include/_field.html' with field=form.email_forward %} {# for the create form #}
                {% include 'include/_field.html' with field=form.homepage %}
                {% include 'include/_field.html' with field=form.source_urls %}
                {% include 'include/_field.html' with field=form.google_plus_page %}
                {% include 'include/_field.html' with field=form.facebook_page %}
                {% include 'include/_field.html' with field=form.twitter_page %}
                {% include 'include/_field.html' with field=form.founded %}
                {% include 'include/_field.html' with field=form.is_private %}
                {% include 'include/_field.html' with field=form.is_active %}
                {% include 'include/_field.html' with field=form.is_live %}
                {% include 'include/_field.html' with field=form.neighbour_distance %}
                {% include 'include/_field.html' with field=form.transregional_distance %}
                {#% include 'include/_field.html' with field=form.can_publish %#}
            </div>

            {% for formset in formsets %}
                <div class="tab-pane {% if active == formset.prefix %}active{% endif %}" id="{{ formset.prefix }}">
                    {% if formset.prefix == 'organisationaddress_set' %}
                        {% include 'include/_static_google_maps_field.html' with field=form.google_maps_url %}
                        {% include 'include/_field.html' with field=form.timezone %}
                        {% include 'include/_field.html' with field=form.coordinates_type %}
                        {% include 'include/_field.html' with field=form.location %}
                    {% endif %}
                    {% include formset.form.template %}
                </div>
            {% endfor %}

        </div>
        <!-- /.tab-content -->

        <div class="form-group">
            <div class="dwbn-form-submit">
                {% block submit_group %}
                    {% if redirect_uri %}
                        <a class="btn btn-default" href="{{ redirect_uri }}">{% trans 'Back' %}</a>{% endif %}
                    {% if perms.organisations.delete_organisation %}
                        <a class="btn btn-default" href="{% url 'organisations:organisation_delete' object.uuid.hex %}">
                            {% trans 'Delete Organisation' %}</a>
                    {% endif %}
                    <button type="submit" class="btn btn-default"
                            name="_continue">{% trans 'Save and continue editing' %}</button>
                    <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
                {% endblock submit_group %}
            </div>
        </div>
    </form>
{% endblock %}

apps/sso/organisations/templates/organisations/organisation_list.html
{% extends 'base_list.html' %}
{% load i18n list tz static thumbnail %}

{% block title %}{% trans 'Organisations' %}{% endblock %}

{% block nav_organisations_organisation_list_class %}active{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
        <li class="active">{% trans 'Organisations' %}</li>
    </ol>
{% endblock breadcrumb %}

{% block navbar %}{% include 'include/global_navigation.html' with active_navigation="organisations" %}{% endblock navbar %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            {% if messages %}{% for message in messages %}
                <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>{% endfor %}
            {% endif %}
        </div>
    </div><!-- /.row -->

    <div class="row dwbn-filter-row">
        <div class="col-sm-3">
            {% include 'include/_search_form.html' %}
        </div>

        <div class="col-sm-9">
            {% for filter in filters %}{% if filter %}
                {% include filter.template_name with filter=filter %}
            {% endif %}{% endfor %}
            <button type="button" class="btn btn-default geo-location {% if cl.params.latlng %}active{% endif %}" data-href="{% query_string cl 'latlng' '' %}"><span
                    class="glyphicon glyphicon-globe"></span> {% trans 'Distance' %}</button>
            <a class="btn btn-default pull-right" href="{% url 'organisations:organisation_list_csv' %}{{ cl.get_query_string }}" role="button" title="{% trans 'Download' %}"><span
                    class="glyphicon glyphicon-download-alt" aria-hidden="true"></span></a>
        </div>
        <!-- /.col-sm-9 -->
    </div>

    <main>
        <div class="col-sm-12 table-responsive">
            <table class="table table-bordered table-striped">
                {% include "include/table_header.html" %}
                <tbody>
                {% for object in object_list %}
                    <tr>
                        <td><a href="{% url 'organisations:organisation_detail' object.uuid.hex %}">{{ object.name }}</a></td>
                        {% with object.organisationpicture_set.first.picture as picture %}
                        <td>
                            {% if picture %}<a href="{{ picture.url }}">{% thumbnail picture "30x30" crop="center" as im %}
                                <img class="dwbn-icon-user" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="">{% endthumbnail %}</a>{% endif %}
                        </td>
                        {% endwith %}
                        <td>{{ object.email|default_if_none:"" }}</td>
                        <td>{% if object.google_maps_url %}<a href="{{ object.google_maps_url }}"><span class="glyphicon glyphicon-map-marker"></span> {{ object.get_coordinates_type_display }}</a>{% endif %}</td>
                        <td>{{ object.organisationaddress_set.first.country.iso2_code }}</td>
                        <td>{{ object.founded|date:"Y-m-d" }}</td>
                        <td>{% if object.is_active %}<span class="glyphicon glyphicon-check"></span>{% else %}<span class="glyphicon glyphicon-unchecked"></span>{% endif %}</td>
                        <td>{%  if object.is_live %}<span class="glyphicon glyphicon-check"></span>{% else %}<span class="glyphicon glyphicon-unchecked"></span>{% endif %}</td>
                        {% if cl.params.latlng %}
                            <td>{% if object.distance %}{{ object.distance.km|floatformat }} km{% endif %}</td>{% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% if is_paginated %}{% pagination page_obj cl %}{% endif %}
        </div>
    </main>
{% endblock content %}

apps/sso/organisations/templates/organisations/organisationcountry_detail.html
{% extends "base_form.html" %}
{% load i18n static %}

{% block title %}{% trans 'Country Details' %}{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
        <li><a href="{% url 'organisations:organisationcountry_list' %}">{% trans 'Countries' %}</a></li>
        <li class="active">{% trans 'Country Details' %}</li>
    </ol>
{% endblock breadcrumb %}


{% block form %}

    {% block message %}{% endblock %}

    <h3>{{ object.country }}</h3>

    {% if messages %}{% for message in messages %}
        <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>{% endfor %}
    {% endif %}


    <div class="row">
        <div class="dwbn-label">{% trans 'Country' %}:</div>
        <div class="dwbn-content">{{ object.country }}</div>
    </div>
    <div class="row">
        <div class="dwbn-label">{% trans 'Homepage' %}:</div>
        <div class="dwbn-content"><a href="{{ object.homepage }}">{{ object.homepage }}</a></div>
    </div>
    <div class="row">
        <div class="dwbn-label">{% trans 'Active' %}:</div>
        <div class="dwbn-content"><span
                class="glyphicon glyphicon-{% if object.is_active %}ok-sign{% else %}minus-sign{% endif %}"></span>
        </div>
    </div>

    <div class="row">
        <div class="dwbn-label">{% trans 'Email address' %}:</div>
        <div class="dwbn-content">{{ object.email|default_if_none:"" }}</div>
    </div>

    <div class="row">
        <div class="dwbn-label">{% trans 'Organisations' %}:</div>
        <div class="dwbn-content"><a href="{% url 'organisations:organisation_list'  %}?country={{ object.country.pk }}">{% trans 'Organisations' %}</a></div>
    </div>

    {% if perms.organisations.change_organisationcountry and has_country_access %}
        {% for emailforward in  object.email.emailforward_set.all %}
            <div class="row">
                <div class="dwbn-label">{% trans 'Email forwarding address' %}:</div>
                <div class="dwbn-content">{{ emailforward }}</div>
            </div>
        {% endfor %}
        {% for emailalias in  object.email.emailalias_set.all %}
            <div class="row">
                <div class="dwbn-label">{% trans 'Email alias address' %}:</div>
                <div class="dwbn-content">{{ emailalias }}</div>
            </div>
        {% endfor %}

        <div class="row">
            <div class="dwbn-label">{% trans 'Country Groups' %}:</div>
            <div class="dwbn-content">
                <ul>
                    {% for group in object.country_groups.all %}
                        <li>{{ group }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endif %}

    <br>

    <div class="form-group">
        <div class="dwbn-form-control_lg">
            {% block submit_group %}

                {% if perms.organisations.change_organisationcountry and has_country_access %}
                    <a class="btn btn-primary"
                       href="{% url 'organisations:organisationcountry_update' object.uuid.hex %}">{% trans 'Update' %}</a>
                {% endif %}

            {% endblock %}
        </div>
    </div>

{% endblock %}