apps/sso/accounts/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetCompleteView
from django.urls import path
from django.views.generic import TemplateView
from .views import PasswordResetView, PasswordResetConfirmView, PasswordChangeDoneView, PasswordCreateConfirmView
from .views import application, PasswordCreateCompleteView, usernote
from .views import emails, confirm_email
from .views import onetimemessage
from .views import organisation
from .views import password_change, profile, contact, delete_profile

app_name = 'accounts'

urlpatterns = [
    path('', application.UserList.as_view(), name='user_list'),
    path('me/', profile, name='profile'),
    path('add/', application.add_user, name='add_user'),
    path('add/done/<uuid:uuid>/', application.add_user_done, name="add_user_done"),
    path('<uuid:uuid>/', application.update_user, name="update_user"),
    path('<uuid:uuid>/delete/', application.UserDeleteView.as_view(), name="delete_user"),
    path('<uuid:uuid>/notes/delete/', usernote.UserNoteDeleteView.as_view(), name="delete_user_note"),
    path('app_admin/', application.AppAdminUserList.as_view(), name='app_admin_user_list'),
    path('app_admin/<uuid:uuid>/', application.app_admin_update_user, name="app_admin_update_user"),
    path('contact/', contact, name='contact'),
    path('contact_thanks/', TemplateView.as_view(template_name="accounts/contact_thanks.html"), name='contact_thanks'),
    path('email/confirm/<str:uidb64>/<str:token>/', confirm_email, name='confirm_email'),
    path('emails/', emails, name='emails'),
    path('profile/delete/', delete_profile, name='delete_profile'),
    path('password_change/', password_change, name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('password_resend/done/', TemplateView.as_view(template_name="accounts/password_resend_done.html"),
         name='password_resend_done'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
    path('reset/<slug:uidb64>/<slug:token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # must be before 'create/<slug:uidb64>/<slug:token>/'
    path('create/done/<slug:uidb64>/', PasswordCreateCompleteView.as_view(), name='password_create_complete'),
    path('create/<slug:uidb64>/<slug:token>/', PasswordCreateConfirmView.as_view(), name='password_create_confirm'),
    path('organisation_change/<int:pk>/', organisation.OrganisationChangeDetailView.as_view(),
         name='organisationchange_detail'),
    path('organisation_change/me/', organisation.OrganisationChangeUpdateView.as_view(), name='organisationchange_me'),
    path('organisation_change/', organisation.OrganisationChangeList.as_view(), name='organisationchange_list'),
    path('organisation_change/<int:pk>/accept/', organisation.OrganisationChangeAcceptView.as_view(),
         name='organisationchange_accept'),
    path('messages/<uuid:uuid>/', onetimemessage.OneTimeMessageView.as_view(), name="view_message"),
]

apps/sso/auth/urls.py
from django.urls import path

from sso.auth.views import LoginView, TokenView, logout
from sso.auth.views.profile import ProfileView, TOTPSetup, PhoneSetupView, AddPhoneView, AddU2FView

app_name = 'auth'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout, name='logout'),
    path('token/<int:device_id>/<str:user_data>/', TokenView.as_view(), name='token'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/totp_setup/', TOTPSetup.as_view(), name='profile_totp_setup'),
    path('profile/add_phone/', AddPhoneView.as_view(), name='add_phone'),
    path('profile/phone_setup/<int:sms_device_id>/', PhoneSetupView.as_view(), name='phone_setup'),
    path('profile/u2f/add_device/', AddU2FView.as_view(), name='u2f_add_device'),
]

apps/sso/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, register_converter
from django.views.generic import RedirectView, TemplateView
from django.views.i18n import JavaScriptCatalog
from smart_selects.views import filterchain
from sso.accounts.forms import UserSelfRegistrationForm2
from sso.admin import sso_admin_site
from sso.oauth2.views import OpenidConfigurationView
from sso.registration.sites import RegistrationSite
from sso.utils.url import UUIDConverter
from sso.views import home

registration_site = RegistrationSite(form_cls=UserSelfRegistrationForm2)

register_converter(UUIDConverter, 'uuid')

urlpatterns = [
    path('', home, name='home'),
    path('.well-known/openid-configuration', OpenidConfigurationView.as_view(), name='openid-configuration'),
    path('jsi18n/', JavaScriptCatalog.as_view(packages=['sso']), name='jsi18n'),
    path('admin/', sso_admin_site.urls),
    path('privacy/', TemplateView.as_view(template_name="privacy.html"), name='privacy'),
    path('about/', RedirectView.as_view(url=settings.SSO_ABOUT, permanent=False), name='about'),
    path('accounts/', include('sso.auth.urls')),
    path('accounts/', include('sso.accounts.urls')),
    path('accounts/', registration_site.urls),
    path('accounts/', include('sso.impersonate.urls')),
    path('organisations/', include('sso.organisations.urls')),
    path('emails/', include('sso.emails.urls')),
    path('oauth2/', include('sso.oauth2.urls')),
    path('api/', include('sso.api.urls')),
    path('chained_filter/organisations/OrganisationCountry/<slug:field>/<slug:value>/', filterchain,
         kwargs={'app': 'organisations', 'model': 'OrganisationCountry', 'manager': 'active_objects'},
         name='chained_filter'),
    path('chained_filter/organisations/AdminRegion/<slug:field>/<slug:value>/', filterchain,
         kwargs={'app': 'organisations', 'model': 'AdminRegion', 'manager': 'active_objects'}, name='chained_filter'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if apps.is_installed('sso.access_requests'):
    urlpatterns += [
        path('extend_access/', include('sso.access_requests.urls')),
    ]

apps/sso/accounts/models/user_data.py
import datetime
import logging

from current_user.models import CurrentUserField
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _, pgettext_lazy
from sso.accounts.models.application import ApplicationRole, RoleProfile
from sso.models import AbstractBaseModel, AddressMixin, PhoneNumberMixin, ensure_single_primary, \
    CaseInsensitiveEmailField, AbstractBaseModelManager
from sso.organisations.models import Organisation, is_validation_period_active

logger = logging.getLogger(__name__)


class UserEmail(AbstractBaseModel):
    MAX_EMAIL_ADRESSES = 2
    email = CaseInsensitiveEmailField(_('email address'), max_length=254, unique=True)
    confirmed = models.BooleanField(_('confirmed'), default=False)
    primary = models.BooleanField(_('primary'), default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta(AbstractBaseModel.Meta):
        verbose_name = _('email address')
        verbose_name_plural = _('email addresses')
        ordering = ['email']

    def __str__(self):
        return self.email


class UserAddress(AbstractBaseModel, AddressMixin):
    ADDRESSTYPE_CHOICES = (
        ('home', pgettext_lazy('address', 'Home')),
        ('work', _('Business')),
        ('other', _('Other')),
    )

    address_type = models.CharField(_("address type"), choices=ADDRESSTYPE_CHOICES, max_length=20)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta(AbstractBaseModel.Meta, AddressMixin.Meta):
        unique_together = (("user", "address_type"),)

    @classmethod
    def ensure_single_primary(cls, user):
        ensure_single_primary(user.useraddress_set.all())


class UserPhoneNumber(AbstractBaseModel, PhoneNumberMixin):
    PHONE_CHOICES = [
        ('home', pgettext_lazy('phone number', 'Home')),  # with translation context
        ('mobile', _('Mobile')),
        ('work', _('Business')),
        ('fax', _('Fax')),
        ('pager', _('Pager')),
        ('other', _('Other')),
    ]
    phone_type = models.CharField(_("phone type"), help_text=_('Mobile, home, office, etc.'), choices=PHONE_CHOICES,
                                  max_length=20)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta(AbstractBaseModel.Meta, PhoneNumberMixin.Meta):
        # unique_together = (("user", "phone_type"),)
        pass

    @classmethod
    def ensure_single_primary(cls, user):
        ensure_single_primary(user.userphonenumber_set.all())


class OneTimeMessage(AbstractBaseModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(_("title"), max_length=255, default='')
    message = models.TextField(_("message"), blank=True, max_length=2048, default='')

    class Meta(AbstractBaseModel.Meta):
        verbose_name = _('one time message')
        verbose_name_plural = _('one time messages')


class OrganisationChangeManager(AbstractBaseModelManager):
    def open(self):
        return self.get(status='o')


class OpenOrganisationChangeManager(AbstractBaseModelManager):
    def get_queryset(self):
        return super().get_queryset().filter(status='o').prefetch_related(
            'user__useremail_set', 'organisation__organisation_country__country')


class OrganisationChange(AbstractBaseModel):
    """
    a request from an user to change the organisation
    """
    STATUS_CHOICES = [
        ('o', _('open')),  # opened by user
        ('c', _('canceled')),  # by user
        ('v', _('approved')),
        ('d', _('denied'))
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    original_organisation = models.ForeignKey(Organisation, related_name='original_organisation', null=True,
                                              blank=True, on_delete=models.CASCADE)
    organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE)
    message = models.TextField(_("message"), max_length=2048,
                               help_text=_('Message for the organisation administrator.'),
                               blank=True)
    comment = models.TextField(_("Comment"), max_length=2048, blank=True)
    status = models.CharField(_('status'), max_length=255, choices=STATUS_CHOICES, default='o')
    last_modified_by_user = CurrentUserField(verbose_name=_('last modified by'),
                                             related_name='organisationchange_last_modified_by',
                                             on_delete=models.SET_NULL)
    completed_by_user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True,
                                          verbose_name=_('completed by'),
                                          related_name='organisationchange_completed_by', on_delete=models.SET_NULL)

    objects = OrganisationChangeManager()
    open = OpenOrganisationChangeManager()

    def cancel(self, user):
        self.status = 'c'
        self.completed_by_user = user
        self.save()

    def verify(self, user):
        self.user.set_organisations([self.organisation])
        self.status = 'v'
        self.completed_by_user = user

        self.user.remove_organisation_related_permissions()

        # check if organisation uses user activation
        if is_validation_period_active(self.organisation):
            if self.user.valid_until is None:
                self.user.valid_until = now() + datetime.timedelta(days=settings.SSO_VALIDATION_PERIOD_DAYS)
        else:
            self.user.valid_until = None
        # save changes and update last_modified field!
        self.user.save()
        self.save()

    def deny(self, user):
        self.status = 'd'
        self.completed_by_user = user
        self.save()

    @property
    def is_open(self):
        return self.status == 'o'

    class Meta(AbstractBaseModel.Meta):
        verbose_name = _('organisation change')
        verbose_name_plural = _('organisation change')

    def get_absolute_url(self):
        return reverse('accounts:organisationchange_detail', kwargs={'pk': self.pk})


class Membership(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE)
    primary = models.BooleanField(_("primary"), default=False)

    class Meta:
        unique_together = (("user", "organisation"),)
        verbose_name = _('organisation membership')
        verbose_name_plural = _('organisation memberships')

    def __str__(self):
        return '%s - %s' % (self.organisation, self.user)

apps/sso/accounts/views/filter.py
import logging

from django.db.models import Q
from django.utils.translation import ugettext_lazy as _
from l10n.models import Country
from sso.views.generic import SearchFilter, ViewChoicesFilter, ViewQuerysetFilter
from sso.accounts.models import ApplicationRole, RoleProfile
from sso.organisations.models import AdminRegion, Organisation, OrganisationCountry

logger = logging.getLogger(__name__)


class UserSearchFilter(SearchFilter):
    search_names = ['username__icontains', 'first_name__icontains', 'last_name__icontains',
                    'useremail__email__icontains']


class UserSearchFilter2(SearchFilter):
    search_names = ['user__username__icontains', 'user__first_name__icontains', 'user__last_name__icontains',
                    'user__useremail__email__icontains']


class IsActiveFilter(ViewChoicesFilter):
    name = 'is_active'
    choices = (('1', _('Active Users')), ('2', _('Inactive Users')))
    select_text = _('active/inactive')
    select_all_text = _("All")
    default = '1'

    def map_to_database(self, qs_name, value):
        return {qs_name: True if (value.pk == "1") else False}


class CountryFilter(ViewQuerysetFilter):
    name = 'country'
    qs_name = 'organisations__organisation_country__country'
    model = Country
    select_text = _('Country')
    select_all_text = _('All Countries')
    all_remove = 'admin_region,center'
    remove = 'admin_region,center,app_role,role_profile,p'
    style = "width: 12em"


class AdminRegionFilter(ViewQuerysetFilter):
    name = 'admin_region'
    qs_name = 'organisations__admin_region'
    model = AdminRegion
    select_text = _('Region')
    select_all_text = _('All Regions')
    all_remove = 'center'
    remove = 'center,app_role,role_profile,p'


class CenterFilter(ViewQuerysetFilter):
    name = 'center'
    qs_name = 'organisations'
    model = Organisation
    select_text = _('Organisation')
    select_all_text = _('All Organisations')
    remove = 'app_role,role_profile,p'
    style = "width: 17em"


class ApplicationRoleFilter(ViewQuerysetFilter):
    name = 'app_role'
    model = ApplicationRole
    select_text = _('Role')
    select_all_text = _('All Roles')

    def apply(self, view, qs, default=''):
        """
        filter with respect to application_roles and role_profiles
        """
        value = self.get_value_from_query_param(view, default)
        if value:
            q = Q(application_roles=value)
            q |= Q(role_profiles__application_roles=value)
            qs = qs.filter(q)
        setattr(view, self.name, value)
        return qs


class RoleProfileFilter(ViewQuerysetFilter):
    name = 'role_profile'
    qs_name = 'role_profiles'
    model = RoleProfile
    select_text = _('Profile')
    select_all_text = _('All Profiles')


########################################################################################
# organisationchange list filter


class OrganisationChangeCountryFilter(ViewQuerysetFilter):
    name = 'country'
    qs_name = 'organisation__organisation_country'
    model = OrganisationCountry
    filter_list = OrganisationCountry.objects.filter(is_active=True).select_related('country')
    select_text = _('Country')
    select_all_text = _('All Countries')
    all_remove = 'admin_region'
    remove = 'admin_region,p'


class OrganisationChangeAdminRegionFilter(ViewQuerysetFilter):
    name = 'admin_region'
    qs_name = 'organisation__admin_region'
    model = AdminRegion
    select_text = _('Region')
    select_all_text = _('All Regions')
    all_remove = ''
    remove = 'p'

apps/sso/accounts/views/onetimemessage.py
import logging

from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView
from django.utils.decorators import method_decorator

from sso.accounts.models import OneTimeMessage

logger = logging.getLogger(__name__)


class OneTimeMessageView(DetailView):
    model = OneTimeMessage
    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user != request.user:
            raise PermissionDenied()
        
        self.object.delete()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

apps/sso/accounts/templates/accounts/contact_thanks.html
{% extends "base_form.html" %}
{% load i18n %}

{% block title %}{{ brand }} | {% trans 'Contact Information' %}{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
    <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
    <li class="active">{% trans 'Feedback' %}</li>
</ol> 
{% endblock breadcrumb %}


{% block form %}
<h1>{% trans 'Feedback' %}</h1>
<p>{% trans "Thank you for your message." %}</p>


{% endblock %}

apps/sso/accounts/templates/accounts/delete_profile_form.html
{% extends "base_form.html" %}
{% load i18n static %}

{% block title %}{% trans 'Profile' %}{% endblock %}

{% block left_content %}{% include 'include/_navigation.html' with active_navigation="profile" %}{% endblock left_content %}

{% block breadcrumb %}
<ol class="breadcrumb">
    <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
    <li class="active">{% trans 'User profile' %}</li>
</ol> 
{% endblock breadcrumb %}


{% block form %}
<form class="form-horizontal" method="post">{% csrf_token %}	
    <div class="">
	    <h3>{% trans 'Delete Profile' %}</h3>
		<p>{% trans "Do you want to delete your account?" %}</p>
		
	    {% if messages %}{% for message in messages %}
	       <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>{% endfor %}
	    {% endif %}
		
		
	    {% if form.errors %}
	        <div class="alert alert-danger">
	        {% if form.errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
	        </div>
	    {% endif %}
    </div>
    <div class="form-group">
        <div class="dwbn-form-control_lg">
	        <button type="submit" class="btn btn-danger">{% trans 'Delete' %}</button>
            &nbsp;{% trans 'or' %}&nbsp; <a class="btn btn-default" href="{% url 'accounts:profile' %}">{% trans 'Cancel' %}</a>            
	    </div>
    </div>
	
	<script>document.getElementById("id_first_name").focus();</script>
	
</form>
{% endblock %}

apps/sso/accounts/templates/accounts/logged_out.html
{% extends "base_site.html" %}
{% load i18n %}

{% block content %}

<p>{% trans "Thanks for spending some quality time with the Web site today." %}</p>

<div class="alert alert-danger">
{% blocktrans %}To protect your privacy:<br>If you are using a shared/public computer, please close all open browser windows and start a new session by opening a new browser window.{% endblocktrans  %}
</div>

<p><a href="{% url 'auth:login' %}">{% trans 'Log in again' %}</a></p>

{% endblock %}

apps/sso/accounts/templates/accounts/organisationchange_accept.html
{% extends "base_form.html" %}
{% load i18n static %}

{% block title %}{% trans 'Accept Organisation Change' %}{% endblock %}

{% block extrascript %}{{ media }}{% endblock extrascript %}


{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
        <li><a href="{% url 'accounts:organisationchange_list' %}">{% trans 'Organisation Changes' %}</a></li>
        <li class="active">{% trans 'Accept Organisation Change' %}</li>
    </ol>
{% endblock breadcrumb %}

{% block form %}
    <form class="form-horizontal" method="post">{% csrf_token %}
        {# Include the hidden fields in the form #}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        <h3>{% trans 'Process Organisation Change' %}</h3>
        <p>
            {% if organisationchange.is_open %}
                {% trans "Please accept or deny the organisation change request." %}
            {% else %}
                <div class="alert alert-info">
                    {% blocktrans with status=organisationchange.get_status_display user=organisationchange.completed_by_user.get_full_name %}The organisation change was already {{ status }} by {{ user }}.{% endblocktrans %}</div>
            {% endif %}
        </p>

        {% if messages %}{% for message in messages %}
            <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>{% endfor %}
        {% endif %}

        {% if form.errors and not form.non_field_errors %}
            <div class="alert alert-danger">
                {% if form.errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}
                    {% trans "Please correct the errors below." %}{% endif %}
            </div>
        {% endif %}

        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}

        {% include 'include/_static_picture_field.html' with field=organisationchange.user.picture %}

        <div class="form-group">
            <label class="control-label">{% trans 'First name' %}</label>

            <div class="dwbn-form-control"><p class="form-control-static">{{ organisationchange.user.first_name }}</p>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label">{% trans 'Last name' %}</label>

            <div class="dwbn-form-control"><p class="form-control-static">{{ organisationchange.user.last_name }}</p>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label">{% trans 'Email address' %}</label>

            <div class="dwbn-form-control"><p
                class="form-control-static">{{ organisationchange.user.primary_email }}</p></div>
        </div>

        <div class="form-group">
            <label class="control-label">{% trans 'Phone number' %}</label>

            <div class="dwbn-form-control"><p
                class="form-control-static">{{ organisationchange.user.primary_phone }}</p></div>
        </div>

        <div class="form-group">
            <label class="control-label">{% trans 'Previous organisation' %}</label>

            <div class="dwbn-form-control"><p
                class="form-control-static">{{ organisationchange.original_organisation|default_if_none:"" }}</p>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label">{% trans 'New organisation' %}</label>

            <div class="dwbn-form-control"><p class="form-control-static">{{ organisationchange.organisation }}</p>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label">{% trans 'Message' %}</label>

            <div class="dwbn-form-control"><p class="form-control-static">{{ organisationchange.message }}</p></div>
        </div>

        {% if organisationchange.is_open %}
            <div class="form-group">
                <div class="dwbn-form-control_lg">
                    {% block submit_group %}
                        <button type="submit" class="btn btn-default" name="_delete">{% trans 'Deny change' %}</button>
                        <button type="submit" class="btn btn-primary">{% trans 'Accept change' %}</button>
                    {% endblock submit_group %}
                </div>
            </div>
        {% endif %}
    </form>
{% endblock %}

apps/sso/accounts/templates/accounts/organisationchange_form.html
{% extends "base_form.html" %}
{% load i18n static %}

{% block title %}{% trans 'Organisation Change Details' %}{% endblock %}

{% block extrascript %}{{ form.media }}{% endblock extrascript %}


{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
        <li><a href="{% url 'accounts:profile' %}">{% trans 'My Account' %}</a></li>
        <li class="active">{% trans 'Update My Organisation' %}</li>
    </ol>
{% endblock breadcrumb %}

{% block form %}
    <form class="form-horizontal" method="post">{% csrf_token %}
        {# Include the hidden fields in the form #}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        <h3>{% trans 'Update My Organisation' %}</h3>

        {% if messages %}{% for message in messages %}
            <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>{% endfor %}
        {% endif %}

        {% if form.errors %}
            <div class="alert alert-danger">
                {% if form.errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}
                    {% trans "Please correct the errors below." %}{% endif %}
            </div>
        {% endif %}

        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}

        {% include 'include/_field.html' with field=form.organisation %}
        {% include 'include/_field.html' with field=form.message %}

        <div class="form-group">
            <div class="dwbn-form-submit">
                {% block submit_group %}
                    {% if redirect_uri %}<a class="btn btn-default" href="{{ redirect_uri }}">{% trans 'Back' %}</a>
                    {% endif %}
                    {% if form.instance.pk %}
                        <button type="submit" class="btn btn-default"
                                name="_cancel">{% trans 'Cancel change of organisation' %}</button>{% endif %}
                    <button type="submit" class="btn btn-default"
                            name="_continue">{% trans 'Save and continue editing' %}</button>
                    <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
                {% endblock submit_group %}
            </div>
        </div>
    </form>
{% endblock %}

apps/sso/accounts/templates/accounts/usernote_confirm_delete.html
{% extends "base_form.html" %}
{% load i18n %}

{% block title %}{% trans 'Delete User' %}{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
    <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
    <li><a href="{% url 'accounts:user_list' %}">{% trans 'User List' %}</a></li>
    <li><a href="{% url 'accounts:update_user' usernote.user.uuid %}{{ usernotes_tab }}">{% trans 'Change User' %}</a></li>
    <li class="active">{% trans 'User Note' %}</li>
</ol>
{% endblock breadcrumb %}

{% block form %}
<form class="form-horizontal" method="post">{% csrf_token %}
    <h3>{% trans 'Delete User Note' %}</h3>

	<div class="form-group">
	  <label class="control-label">{% trans 'username' %}</label>
	  <div class="dwbn-form-control"><p class="form-control-static">{{ object.user }}</p></div>
	</div>

    <div class="form-group">
      <label class="control-label">{% trans 'Created by' %}</label>
      <div class="dwbn-form-control"><p class="form-control-static">{{ object.created_by_user }}</p></div>
    </div>

    <div class="form-group">
      <label class="control-label">{% trans 'Note' %}</label>
      <div class="dwbn-form-control"><p class="form-control-static">{{ object.note }}</p></div>
    </div>

    <div class="form-group">
      <label class="control-label">{% trans 'last modified' %}</label>
      <div class="dwbn-form-control"><p class="form-control-static">{{ object.last_modified }}</p></div>
    </div>

    <div class="form-group">
        <div class="dwbn-form-control_lg">
            <button type="submit" class="btn btn-danger">{% trans 'Confirm Delete' %}</button>
            {% if cancel_url %}&nbsp;{% trans 'or' %}&nbsp; <a class="btn btn-default" href="{{ cancel_url }}{{ usernotes_tab }}">{% trans 'Cancel' %}</a>{% endif %}
        </div>
   </div>
</form>
{% endblock %}